/**
 * Controller for creating and interacting with Clients
 * Created By: Fiona Cheng
 * Date Created: October 24, 2025
 */

package org.example;
import jakarta.servlet.http.HttpSession;
import org.springframework.beans.factory.annotation.Autowired;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.*;

import java.util.Map;
import java.util.Optional;

@Controller
public class ClientController {

    private static final Logger logger = LoggerFactory.getLogger(ClientController.class);

    @Autowired
    private ClientRepository clientRepository;

    /**
     * POST /client/register
     * Creates a new client.
     *
     * Example curl command for Windows:
     * -------------------------------------------
     * curl -X POST http://localhost:8080/client/register -H "Content-Type:
     * application/json" -d "{\"username\": \"Bob\", \"password\": \"myPassword\", \"isOwner\": \"false\"}"
     * -------------------------------------------
     *
     * Expected JSON response:
     * -------------------------------------------
     * {"id":1,"isOwner":false,"username":"Bob","password":"myPassword","shoppingCart":[],"purchasedBooks":[]}
     * -------------------------------------------
     */
    @PostMapping("/client/register")
    public ResponseEntity<Client> createClient(@RequestBody Client client) {
        // The ID will be autogenerated by JPA when saved
        Client savedClient = clientRepository.save(client);
        logger.info("Created Client: {}", savedClient.getUsername());
        return ResponseEntity.ok(savedClient);
    }

    /**
     * GET /client/id/{id}
     * Returns a JSON Client object based on the ID.
     *
     * Example curl command for Windows:
     * -------------------------------------------
     * curl -X GET http://localhost:8080/client/id/1 -H "Accept: application/json"
     * -------------------------------------------
     *
     * Expected JSON response:
     * -------------------------------------------
     * {"id":1,"isOwner":false,"username":"Bob","password":"myPassword","shoppingCart":[],"purchasedBooks":[]}
     * -------------------------------------------
     */
    @GetMapping("/client/id/{id}")
    public ResponseEntity<Client> getClientById(@PathVariable Integer id) {
        return clientRepository.findById(id)
                .map(ResponseEntity::ok)
                .orElse(ResponseEntity.notFound().build());
    }

    /**
     * POST /client/login
     * Attempts to log in a client using the provided username and password.
     * On success, stores the client in the HTTP session.
     *
     * Example curl command for Windows:
     * -------------------------------------------
     * curl -X POST http://localhost:8080/client/login -H "Content-Type: application/json" -d "{\"username\": \"Bob\", \"password\": \"myPassword\"}"
     * -------------------------------------------
     *
     * Possible JSON responses:
     * -------------------------------------------
     * Success:
     * {"message":"Login successful"}
     *
     * Failure - username not found:
     * "User not found" (HTTP 401)
     *
     * Failure - incorrect password:
     * "Invalid password" (HTTP 401)
     * -------------------------------------------
     *
     * @param credentials JSON object containing "username" and "password" fields
     * @param session     HTTP session used to persist logged-in user
     * @return ResponseEntity containing success message or error
     */
    @PostMapping("/client/login")
    public ResponseEntity<?> loginClient(@RequestBody Map<String, String> credentials, HttpSession session) {
        String username = credentials.get("username");
        String password = credentials.get("password");

        Optional<Client> clientOpt = clientRepository.findByUsername(username);
        if (clientOpt.isEmpty()) {
            logger.error("User {} does not exist.",  username);
            return ResponseEntity.status(HttpStatus.UNAUTHORIZED).body("User not found");
        }

        Client client = clientOpt.get();

        if (!client.getPassword().equals(password)) {
            return ResponseEntity.status(HttpStatus.UNAUTHORIZED).body("Invalid password");
        }

        // Store in session
        session.setAttribute("loggedInClient", client);
        logger.info("Client {} logged in", client.getUsername());
        return ResponseEntity.ok(Map.of("message", "Login successful"));
    }

    /**
     * GET /client/me
     * Returns the currently logged-in client based on the HTTP session.
     *
     * Example curl command for Windows:
     * -------------------------------------------
     * curl -X GET http://localhost:8080/client/me -H "Accept: application/json"
     * -------------------------------------------
     *
     * Possible JSON responses:
     * -------------------------------------------
     * If logged in:
     * {"id":1,"isOwner":false,"username":"Bob","shoppingCartIds":[2,5],"purchasedBookIds":[1,3]}
     *
     * If not logged in:
     * "Not logged in" (HTTP 401)
     * -------------------------------------------
     *
     * @param session HTTP session used to retrieve the logged-in client
     * @return ResponseEntity containing the client DTO or error message
     */
    @GetMapping("/client/me")
    public ResponseEntity<?> getCurrentUser(HttpSession session) {
        Client client = (Client) session.getAttribute("loggedInClient");
        if (client == null) {
            return ResponseEntity.status(HttpStatus.UNAUTHORIZED).body("Not logged in");
        }
        return ResponseEntity.ok(client);
    }

    /**
     * POST /client/logout
     * Logs out the current client by invalidating the HTTP session.
     *
     * Example curl command for Windows:
     * -------------------------------------------
     * curl -X POST http://localhost:8080/client/logout
     * -------------------------------------------
     *
     * Expected JSON response:
     * -------------------------------------------
     * {"message":"Logged out successfully"}
     * -------------------------------------------
     *
     * @param session HTTP session to invalidate
     * @return ResponseEntity confirming logout
     */
    @PostMapping("/client/logout")
    public ResponseEntity<?> logout(HttpSession session) {
        session.invalidate();
        return ResponseEntity.ok(Map.of("message", "Logged out successfully"));
    }

    /**
     * GET /client/username/{username}
     * Returns a JSON Client object based on the ID.
     *
     * Example curl command for Windows:
     * -------------------------------------------
     * curl -X GET http://localhost:8080/client/username/Bob -H "Accept: application/json"
     * -------------------------------------------
     *
     * Expected JSON response:
     * -------------------------------------------
     * {"id":1,"isOwner":false,"username":"Bob","password":"myPassword","shoppingCart":[],"purchasedBooks":[]}
     * -------------------------------------------
     */
    @GetMapping("/client/username/{username}")
    public ResponseEntity<Client> getClientByUsername(@PathVariable String username) {
        return clientRepository.findByUsername(username)
                .map(ResponseEntity::ok)
                .orElse(ResponseEntity.notFound().build());
    }

    /**
     * POST /client/cart/add/{bookId}
     * Adds a book ID to the current client's shopping cart
     * It is expected that the user is already logged in
     *
     * Example curl command for Windows:
     * -------------------------------------------
     * curl -X POST http://localhost:8080/client/cart/add/5
     * -------------------------------------------
     *
     * Expected JSON response (updated client):
     * -------------------------------------------
     * {
     *   "id": 1,
     *   "username": "Bob",
     *   "isOwner": false,
     *   "password": "myPassword",
     *   "shoppingCart": [5],
     *   "purchasedBooks": []
     * }
     * -------------------------------------------
     */
    @PostMapping("/client/cart/add/{bookId}")
    public ResponseEntity<?> addBookToCart(@PathVariable Long bookId, HttpSession session) {
        // Get the current client
        Client client = (Client) session.getAttribute("loggedInClient");
        if (client == null) {
            logger.error("ERROR: User is not logged in to add to cart.");
            return ResponseEntity.status(HttpStatus.UNAUTHORIZED).body("Not logged in");
        }

        // Add the book to the client's shopping cart
        client.addToShoppingCart(bookId);
        clientRepository.save(client);
        logger.info("Added book: {} to client {} shopping cart", bookId, client.getUsername());

        return ResponseEntity.ok(client);
    }

    /**
     * POST /client/cart/remove/{bookId}
     * Removes a book ID from the current client's shopping cart
     * It is expected that the user is already logged in
     *
     * Example curl command for Windows:
     * -------------------------------------------
     * curl -X POST http://localhost:8080/client/cart/remove/5
     * -------------------------------------------
     *
     * Expected JSON response (updated client):
     * -------------------------------------------
     * {
     *   "id": 1,
     *   "username": "Bob",
     *   "isOwner": false,
     *   "password": "myPassword",
     *   "shoppingCart": [],
     *   "purchasedBooks": []
     * }
     * -------------------------------------------
     */
    @PostMapping("/client/cart/remove/{bookId}")
    public ResponseEntity<?> removeBookFromCart(@PathVariable Long bookId, HttpSession session) {
        // Get the current client
        Client client = (Client) session.getAttribute("loggedInClient");
        if (client == null) {
            logger.error("ERROR: User is not logged in to remove from cart.");
            return ResponseEntity.status(HttpStatus.UNAUTHORIZED).body("Not logged in");
        }

        // Add the book to the client's shopping cart
        client.removeFromShoppingCart(bookId);
        clientRepository.save(client);
        logger.info("Removed book: {} from client {} shopping cart", bookId, client.getUsername());

        return ResponseEntity.ok(client);
    }
}
