/**
 * Controller for creating and interacting with Clients
 * Created By: Fiona Cheng
 * Date Created: October 24, 2025
 */

package org.example;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.ResponseEntity;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.*;

@Controller
public class ClientController {

    @Autowired
    private ClientRepository clientRepository;

    /**
     * POST /client/create
     * Creates a new client.
     *
     * Example curl command for Windows:
     * -------------------------------------------
     * curl -X POST http://localhost:8080/client/create -H "Content-Type:
     * application/json" -d "{\"username\": \"Bob\", \"password\": \"myPassword\", \"isOwner\": \"false\"}"
     * -------------------------------------------
     *
     * Expected JSON response:
     * -------------------------------------------
     * {"id":1,"isOwner":false,"username":"Bob","password":"myPassword","shoppingCart":[],"purchasedBooks":[]}
     * -------------------------------------------
     */
    @PostMapping("/client/create")
    public ResponseEntity<Client> createClient(@RequestBody Client client) {
        // The ID will be autogenerated by JPA when saved
        Client savedClient = clientRepository.save(client);
        return ResponseEntity.ok(savedClient);
    }

    /**
     * GET /client/{id}
     * Returns a JSON Client object based on the ID.
     *
     * Example curl command for Windows:
     * -------------------------------------------
     * curl -X GET http://localhost:8080/client/1 -H "Accept: application/json"
     * -------------------------------------------
     *
     * Expected JSON response:
     * -------------------------------------------
     * {"id":1,"isOwner":false,"username":"Bob","password":"myPassword","shoppingCart":[],"purchasedBooks":[]}
     * -------------------------------------------
     */
    @GetMapping("/client/{id}")
    public ResponseEntity<Client> getClientById(@PathVariable Integer id) {
        return clientRepository.findById(id)
                .map(ResponseEntity::ok)
                .orElse(ResponseEntity.notFound().build());
    }
}
